/**
 * Ascom Prisoner API
 * This is the Ascom REST Interface for Locations, Users, Persons and Appointments. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alessandro.marra@ascom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param religions 
 * @param balance 
 * @param lawyer 
 * @param socialWorker 
 * @param authority 
 * @param polisNr 
 * @param hkNr 
 * @param delict 
 */
data class PersonSecondaryData (

    val religions: kotlin.Array<kotlin.String>? = null,
    val balance: kotlin.Float? = null,
    val lawyer: kotlin.String? = null,
    val socialWorker: kotlin.String? = null,
    val authority: kotlin.String? = null,
    val polisNr: kotlin.String? = null,
    val hkNr: kotlin.String? = null,
    val delict: kotlin.String? = null
) {
}