/**
 * Ascom Prisoner API
 * This is the Ascom REST Interface for Locations, Users, Persons and Appointments. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alessandro.marra@ascom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.PersonLocation

/**
 * 
 * @param id 
 * @param rfId 
 * @param firstName 
 * @param lastName 
 * @param middleName 
 * @param birthDate 
 * @param detention Indicates the Detention Type
 * @param gender 0 Male, 1 Female, 2 Other, 3 Undefined
 * @param attention Indicate if a Person has some special behaviors
 * @param collusion Indicate if a Person has collusion with other Persons
 * @param picture Indicates if a picture is available
 * @param assigned Indicates if the requesting user is assigned to this person
 * @param locations 
 */
data class PersonBasic (

    val id: kotlin.String? = null,
    val rfId: kotlin.String? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val middleName: kotlin.String? = null,
    val birthDate: java.time.LocalDate? = null,
    /* Indicates the Detention Type */
    val detention: kotlin.String? = null,
    /* 0 Male, 1 Female, 2 Other, 3 Undefined */
    val gender: kotlin.Int? = null,
    /* Indicate if a Person has some special behaviors */
    val attention: kotlin.Boolean? = null,
    /* Indicate if a Person has collusion with other Persons */
    val collusion: kotlin.Boolean? = null,
    /* Indicates if a picture is available */
    val picture: kotlin.Boolean? = null,
    /* Indicates if the requesting user is assigned to this person */
    val assigned: kotlin.Boolean? = null,
    val locations: kotlin.Array<PersonLocation>? = null
) {
}