/**
 * Ascom Prisoner API
 * This is the Ascom REST Interface for Locations, Users, Persons and Appointments. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alessandro.marra@ascom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Location
import io.swagger.client.models.Role

/**
 * 
 * @param id 
 * @param name 
 * @param parentId 
 * @param parentName 
 * @param roles 
 * @param locations 
 */
data class Unit (

    val id: kotlin.Int? = null,
    val name: kotlin.String? = null,
    val parentId: kotlin.Int? = null,
    val parentName: kotlin.String? = null,
    val roles: kotlin.Array<Role>? = null,
    val locations: kotlin.Array<Location>? = null
) {
}